### PR TITLE
Merge changes from "master" branch into "spi" branch

### PR DESCRIPTION
**Pull request by frazar**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@frazar could you briefly explain why you want to merge spi branch onto master?

**Comment by frazar** [comment]
It's the other way around. The master branch contains some changes to the "install.sh" and "start.sh" files that have accumulated in the years and have not been merged into the spi branch.

**Comment by gonzalocasas** [comment]
@frazar yes, sorry, it's the other way around. But the remark about changes in master not in spi is not correct. On one hand, the spi and master branches are intentionally separated to support ubs and spi boards. On the other, the most updated branch is actually spi, so this pr is actually regressing things on the spi branch, in particular support for the new naming of network interfaces on Debian.

**Comment by frazar** [comment]
Oh, I see. I saw the updated README instructions and got confused. My bad..

**Comment by gonzalocasas** [comment]
👍

**Comment by frazar** [comment]
Would you still be intersted in 
- a PR merging the README updates from branch master to spi, or
- another PR merging the new network interface naming into master?

**Comment by gonzalocasas** [comment]
@frazar the latter, definitely! The former, maybe not so much because the up-to-date instructions for the SPI version are on this wiki. Eventually, we could rework the whole thing, merge everything in master with a script that asks if it's spi or usb, and does different things accordingly.

**Pull request closed without merging**
