### PR TITLE
add instruction to avoid regular password request

### PR DESCRIPTION
**Pull request by abouillot**
By adding ttn user in sudoers file, the system will not ask root password at every sudo commands

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@abouillot: I get this is more convenient, but isn't `NOPASSWD` generally consider a security no-go?

**Comment by abouillot** [comment]
I guess this can be a long debate, as the two sounds can be found on Internet. Maybe some warning wording to let user know what he's about to do.

**Comment by gonzalocasas** [comment]
Fair enough! Do you think we should add a small remark in the same line or is it ok as it is?

**Comment by abouillot** [comment]
I've added some words about the potential risk, and indicated this is optionnal.

**Comment by gonzalocasas** [comment]
Thanks!

**Pull request merged**
